# Defines three organizations
#  - Orderer organization
#  - Org1  = Single peer organization
#    Uses the "Specs" to declare the peers instead of Template
#  - Org2  = Another peer organization
# SOLUTION to the exercise

##### Orderer for secureOrderer
OrdererOrgs:
  - Name: Orderer
    Domain: secureOrderer.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for secureOrderer
PeerOrgs:
  # Peer configuration for secureOrderer
  - Name: Org1
    Domain: secureOrderer.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: firstOrg
        CommonName: firstOrg
    Users:
      Count: 2

  # Peer configuration for secOrg
  - Name: Org2
    Domain: secOrg.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: peer1
        CommonName: peer1
    Users:
      Count: 1



      