# Defines four organizations
#  - Orderer organization
#  - secureOrderer
#  - secOrg
#  - Expo
##### Orderer for secureOrderer
OrdererOrgs:
  - Name: Orderer
    Domain: secureOrderer.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for secureOrderer
PeerOrgs:
  # Peer configuration for secureOrderer
  - Name: secureOrderer
    Domain: secureOrderer.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.secureOrderer.com
        CommonName: peer1.secureOrderer.com
    Users:
      Count: 1

  # Peer configuration for secOrg
  - Name: secOrg
    Domain: secOrg.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.secOrg.com
        CommonName: peer1.secOrg.com
    Users:
      Count: 1

  # Peer configuration for secOrg
  - Name: Expo
    Domain: expo.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.expo.com
        CommonName: peer1.expo.com
    Users:
      Count: 1


      