##### Defines two organizations   ####

##### Orderer for airline network ####
OrdererOrgs:
  - Name: Orderer
    Domain: secureOrderer.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
PeerOrgs:
  #### Peers for secureOrderer airline
  - Name: secureOrderer
    Domain: secureOrderer.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: firstOrg
        CommonName: firstOrg
    Users:
      Count: 1
  #### Peers for secOrg airline
  - Name: secOrg
    Domain: secOrg.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: firstOrg
        CommonName: firstOrg
    Users:
      Count: 1

  - Name: expo
    Domain: expo.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: firstOrg
        CommonName: firstOrg
    Users:
      Count: 1


      