
# policy.0
# Minimalistic setup to show the working of the default Policy setup
# There are 3 organizations defined in this setup. Orderer - secureOrderer - secOrg    
# THIS DOES NOT WORKS as POLICIES ARE REQUIRED in 2.x    

# ORGANIZATIONS
Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/secureOrderer.com/msp


  - &secureOrderer
    Name: secureOrderer
    ID: secureOrdererMSP
    MSPDir: ./crypto-config/peerOrganizations/secureOrderer.com/msp
    AnchorPeers:
      - Host: localhost
        Port: 7051

  - &secOrg
    Name: secOrg
    ID: secOrgMSP
    MSPDir: ./crypto-config/peerOrganizations/secOrg.com/msp
    AnchorPeers:
      - Host: localhost
        Port: 8051

#   ORDERER
Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - localhost:7050

  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 2s

  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Capabilities:


Application: &ApplicationDefaults
 
  Organizations:

  Capabilities:
 

#   CHANNEL
Channel: &ChannelDefaults

  Capabilities:

  
#   PROFILES
Profiles:

  AirlineOrdererGenesis:
      <<: *ChannelDefaults
      Orderer:
          <<: *OrdererDefaults
          Organizations:
              - <<: *Orderer


      Application:
            <<: *ApplicationDefaults

            Organizations:
                - <<: *secureOrderer
                - <<: *secOrg
                 

      Consortiums:

        CTIConsortium:
            
            Organizations:
                  - <<: *secureOrderer
                  - <<: *secOrg
                                
                  
  AirlineChannel:
    <<: *ChannelDefaults
    Consortium: CTIConsortium
        
    Application:
        <<: *ApplicationDefaults
        
        Organizations:
            - <<: *secureOrderer
            - <<: *secOrg
        


  