# Defines two organizations
#  - Orderer organization
#  - Org1  = Single peer organization
#    Uses the "Specs" to declare the peers instead of Template

##### Orderer for secureOrderer
OrdererOrgs:
  - Name: Orderer
    Domain: secureOrderer.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for secureOrderer
PeerOrgs:
  # Peer configuration for secureOrderer
  - Name: Org1
    Domain: secureOrderer.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: firstOrg
        CommonName: firstOrg
    Users:
      Count: 2



      