# Defines single organizations
#  - Orderer organization

##### Orderer for secureOrderer
OrdererOrgs:
  - Name: Orderer
    Domain: secureOrderer.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      




      